### ISSUE TITLE
When standing on something, if your head is touching a platform, you can keep walking in the air under the upper platform

### ISSUE THREAD

**Issue by epenning** [epenning/flippy-flop#32]
Steps for production:
1. Open Sprint 1 Level
2. Navigate to far bottom-left platform
3. Flip upside down
4. Walk right off the platform (now standing on a wide obstacle)
5. Walk left off the obstacle, but move right in the air so you land on the tall obstacle
6. Walk right

Expected behavior: fall off the tall obstacle
Actual behavior: standing in air with top of head sliding along attached to upper platform

Note: this also messes up the flipping really badly

**Comment by epenning** [comment]
![image](https://cloud.githubusercontent.com/assets/8647254/18646955/7701f9b2-7e79-11e6-877d-ce5597c460ff.png)

**Comment by r-escobar** [comment]
Fixed (see lines 214-218 in PlayerController)
